Add the ability to disable individual rules per-buffer
editorconfig/editorconfig-vim pull request #155
Opened 2020-10-19 04:30 UTC by midchildan

This change introduces a buffer-local version of `g:EditorConfig_disable_rules`. It's useful in cases where EditorConfig
rules are in conflict with the file syntax, e.g. space indents in Makefiles.

Somewhat related to #154

2020-10-20 16:54 UTC, cxw42 requested changes
I understand the problem you mention: incorrect .editorconfig settings for Makefiles can cause issues.  However, I think that fixing the `.editorconfig` files for those projects would be a more consistent solution than disabling specific rules.  The overall goal of EditorConfig is consistency, and permitting users to pick and choose rules is more likely to break consistency than to promote it.

Example: suppose I am working on a project with a broken `.editorconfig`, and I add a disable-rules to my `vimrc`.  Then that project will not experience breakage.  Suppose I then switch to a different project, but forget to remove the disable-rules from `vimrc`.  I will think the EditorConfig settings are all being applied, when in fact they are not.

(Of course, you can always run your own fork of the plugin with whatever features you want, even if this PR doesn't get merged :) .)

2020-10-20 19:32 UTC, xuhdev reviewed
I agree with @cxw42 . The EditorConfig website says:

> EditorConfig helps maintain consistent coding styles for multiple developers working on the same project across various editors and IDEs.

If the settings of Makefile is incorrect, it's better to correct the `.editorconfig` files to make it consistently correct across all editors, than to add hot fixes to each editor plugin.

Are there other specific applications you have in your mind?

2020-10-21 00:24 UTC, cxw42 commented
I had forgotten until just now that we have `g:EditorConfig_disable_rules` (#89, #90).  If it were up to me, I would remove that variable as well, so please don't think of it as a model :) .

2020-10-21 00:35 UTC, midchildan commented
> Are there other specific applications you have in your mind?

I haven't run into this problem outside of Makefiles, but I do run into it often because I occasionally write my own personal Makefiles for projects that doesn't have one. I just currently disable EditorConfig altogether for Makefiles, but I thought it'd be great if I can only disable rules that's causing a problem. However, I do think this is a minority use case, so I'm happy with closing this PR though.

2020-10-21 00:55 UTC, cxw42 commented
@midchildan Thanks very much for your understanding!  For what it's worth, I have never had a PR rejected for adding a .editorconfig file ;) .  Happy hacking!

2020-10-21 00:55 UTC, closed without merging